[bootstrap.packages]
"brew:yt-dlp" = "latest"

[dotfiles]
"~/.bin/*" = { source = "~/.dotfiles/yt-dlp/bin/*", mode = "symlink" }
"~/.config/yt-dlp/config" = { source = "~/.dotfiles/yt-dlp/config", mode = "symlink" }
