[bootstrap.packages]
"brew:bash" = "latest"
"brew:bat" = "latest"
"brew:btop" = "latest"
"brew:dust" = "latest"
"brew:eza" = "latest"
"brew:fzf" = "latest"
"brew:glow" = "latest"
"brew:jq" = "latest"
"brew:yq" = "latest"
"brew:ocrmypdf" = "latest"
"brew:pandoc" = "latest"
"brew:starship" = "latest"
"brew:tesseract" = "latest"
"brew:vhs" = "latest"
"brew:zoxide" = "latest"
"brew:zsh" = "latest"
"brew:coreutils" = { version = "latest", os = "macos" }
"brew:libyaml" = { version = "latest", os = "macos" }
"brew:gawk" = { version = "latest", os = "macos" }
"brew:gnu-sed" = { version = "latest", os = "macos" }
"brew:gnu-tar" = { version = "latest", os = "macos" }
"brew:gnu-which" = { version = "latest", os = "macos" }
"brew:gnupg" = { version = "latest", os = "macos" }
"brew:grep" = { version = "latest", os = "macos" }
"apt:command-not-found" = { version = "latest", os = "linux" }

[bootstrap.repos]
"~/.zgenom" = { url = "https://github.com/jandamm/zgenom.git" }

[bootstrap.mise_shell_activate]
zshrc = "activate"

[dotfiles]
"~/.bin/*" = { source = "~/.dotfiles/shell/bin/*", mode = "symlink" }
"~/.aliases" = { source = "~/.dotfiles/shell/aliases", mode = "symlink" }
"~/.profile" = { source = "~/.dotfiles/shell/profile", mode = "symlink" }
"~/.zshrc" = { source = "~/.dotfiles/shell/zshrc", mode = "symlink" }
"~/.config/atuin/*" = { source = "~/.dotfiles/shell/config/atuin/*", mode = "symlink" }
"~/.config/glow/*" = { source = "~/.dotfiles/shell/config/glow/*", mode = "symlink" }
"~/.config/starship.toml" = { source = "~/.dotfiles/shell/config/starship.toml", mode = "symlink" }

[tools]
atuin = "latest"
dotnet = ["9", "10"]
lua = "latest"
go = "latest"
node = "latest"
python = "latest"
