[bootstrap.packages]
"brew:git" = "latest"
"brew:git-lfs" = "latest"
"brew:hunk" = "latest"

[dotfiles]
"~/.bin/diff-highlight" = { source = "~/.dotfiles/git/bin/diff-highlight", mode = "symlink" }
"~/.gitconfig" = { source = "~/.dotfiles/git/gitconfig", mode = "symlink" }
"~/.gitignore" = { source = "~/.dotfiles/git/gitignore", mode = "symlink" }
