#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

mem_size_gb=0
if [[ "$(uname)" == "Darwin" ]]; then
  # assumes shared RAM/VRAM
  mem_size=$(sysctl -n hw.memsize)
  mem_size_gb=$((mem_size / 1024 ** 3))
elif [[ "$(uname)" == "Linux" ]]; then
  mem_size=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader | awk '{s+=$1} END {print s}')
  mem_size_gb=$((mem_size / 1000))
fi

# assemble a list of models that can be loaded
models=()
if ((mem_size_gb >= 16)); then
  models+=("7B")
fi
if ((mem_size_gb >= 8)); then
  models+=("3B")
fi
models+=("1.5B")

model=$(gum choose --header "FIM Model" "${models[@]}")

llama-server --hf-repo "ggml-org/Qwen2.5-Coder-${model}-Q8_0-GGUF" --hf-file "qwen2.5-coder-${model,,}-q8_0.gguf" -c 2048
