#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

content=$(cat "${1:--}")

model=$(select-model --header "Summarizer Model")

exec ollama run --hidethinking "$model" "Summarize the following text. Do not provide commentary:\n${content}" | glow -p
