[bootstrap.packages]
"brew:vim" = "latest"

[dotfiles]
"~/.vimrc" = { source = "~/.dotfiles/vim/vimrc", mode = "symlink" }
"~/.vim/colors/nord.vim" = { source = "~/.dotfiles/vim/config/colors/nord.vim", mode = "symlink" }
