#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

function charToNato() {
  case "$1" in
  A | a) echo "Alpha" ;;
  B | b) echo "Bravo" ;;
  C | c) echo "Charlie" ;;
  D | d) echo "Delta" ;;
  E | e) echo "Echo" ;;
  F | f) echo "Foxtrot" ;;
  G | g) echo "Golf" ;;
  H | h) echo "Hotel" ;;
  I | i) echo "India" ;;
  J | j) echo "Juliet" ;;
  K | k) echo "Kilo" ;;
  L | l) echo "Lima" ;;
  M | m) echo "Mike" ;;
  N | n) echo "November" ;;
  O | o) echo "Oscar" ;;
  P | p) echo "Papa" ;;
  Q | q) echo "Quebec" ;;
  R | r) echo "Romeo" ;;
  S | s) echo "Sierra" ;;
  T | t) echo "Tango" ;;
  U | u) echo "Uniform" ;;
  V | v) echo "Victor" ;;
  W | w) echo "Whiskey" ;;
  X | x) echo "X-ray" ;;
  Y | y) echo "Yankee" ;;
  Z | z) echo "Zulu" ;;
  0) echo "Zero" ;;
  1) echo "One" ;;
  2) echo "Two" ;;
  3) echo "Three" ;;
  4) echo "Four" ;;
  5) echo "Five" ;;
  6) echo "Six" ;;
  7) echo "Seven" ;;
  8) echo "Eight" ;;
  9) echo "Nine" ;;
  *) echo "${char}" ;;
  esac
}

text="$*"
length=${#text}

for ((i = 0; i < length; i++)); do
  char="${text:i:1}"
  nato=$(charToNato "$char")
  echo "$((i + 1)). ${nato}"
done
