[bootstrap.hooks.pre-packages]
run = '~/.dotfiles/discord/bin/install-discord'

[bootstrap.packages]
"brew:curl" = "latest"
"brew-cask:discord" = { version = "latest", os = "macos" }

[dotfiles]
"~/.bin/*" = { source = "~/.dotfiles/discord/bin/*", mode = "symlink" }
