[bootstrap.packages]
"brew:llama.cpp" = { version = "latest", os = "macos" }
"brew:openai-whisper" = "latest"

[bootstrap.hooks.post-packages]
run = "~/.dotfiles/ai/setup_linux.sh"

[tools]
pi = "latest"
rtk = "latest"

[dotfiles]
"~/.bin/*" = { source = "~/.dotfiles/ai/bin/*", mode = "symlink" }
"~/.pi" = { source = "~/.dotfiles/ai/pi", mode = "symlink" }
