[bootstrap.packages]
# required
"brew:tmux" = "latest"
"brew:bash" = "latest"

# plugin: now playing
"brew:nowplaying-cli" = { os = "darwin" }
"apt:playerctl" = { os = "linux" }

# plugin: weather
"brew:curl" = "latest"

# plugin: netspeed
"brew:ifstat" = "latest"

# nerd fonts
"brew-cask:font-caskaydia-mono-nerd-font" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-hack-nerd-font" = "latest"

[bootstrap.repos]
"~/.tmux/plugins/tpm" = { url = "https://github.com/tmux-plugins/tpm.git" }

[dotfiles]
"~/.tmux.conf" = { source = "~/.dotfiles/tmux/tmux.conf", mode = "symlink" }

# post dotfiles because tmux.conf is needed, and dotfiles follow repos
[bootstrap.hooks.post-dotfiles]
run = "~/.tmux/plugins/tpm/scripts/install_plugins.sh"
