#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

tmpfile=$(mktemp)

trap 'rm -f ${tmpfile}.en.vtt' EXIT

yt-dlp \
  --skip-download \
  --write-subs \
  --sub-lang en \
  --output "${tmpfile}" \
  "$@"

cat "${tmpfile}.en.vtt" | sed 's/<[^>]*>//g'
