#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

format="bestvideo*+bestaudio"

TEMP=$(getopt --options f:Fh --long format:,list-formats,help -- "$@")
eval set -- "$TEMP"

while true; do
  case "$1" in
  -f | --format)
    format=$2
    shift 2
    ;;
  -F | --list-formats)
    exec yt-dlp --list-formats "$@"
    ;;
  -h | --help)
    echo "Usage: $0 [-f FORMAT | --format FORMAT] [-F | --list-formats] [-h | --help] URL"
    exit 0
    ;;
  --)
    shift
    break
    ;;
  *)
    echo "Invalid option: $1"
    exit 1
    ;;
  esac
done

exec yt-dlp \
  --format "${format}" \
  --output '%(title)s.%(ext)s' \
  --merge-output-format mp4 \
  --embed-thumbnail \
  --embed-metadata \
  --write-subs \
  --sub-lang en \
  "$@"
