# Refer to https://starship.rs/config/
# and https://www.nerdfonts.com/cheat-sheet
continuation_prompt = "[󰇘 ](blue)"

format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
[](fg:#394260 bg:#212736)\
$ruby\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""

[character]
success_symbol = "[❱](green)"
error_symbol = "[❱](red)"
vicmd_symbol = "[❰](cyan)"

[cmd_duration]
style = "bg:#1d2230"
format = "[$duration](fg:3 bg:#1d2230)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_state]
style = "bg:#394260"
format = '[\($state($progress_current/$progress_total)\)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($ahead_behind $all_status )](fg:#769ff0 bg:#394260)]($style)'
conflicted = "[[󰦎${count}](fg:5 bg:#394260)]($style)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "[[?${count}](fg:7 bg:#394260)]($style)"
stashed = "[[\\$${count}](fg:6 bg:#394260)]($style)"
modified = "[[~${count}](fg:3 bg:#394260)]($style)"
staged = "[[+${count}](fg:2 bg:#394260)]($style)"
renamed = "[[»${count}](fg:4 bg:#394260)]($style)"
deleted = "[[✘${count}](fg:9 bg:#394260)]($style)"

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[os]
format = "[$symbol]($style)"
style = "fg:prim bg:sec"
disabled = false

[os.symbols]
Debian = ""
Linux = ""
Macos = ""
Raspbian = ""
Windows = ""
Ubuntu = ""
Unknown = ""

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ruby]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
